# Generated by Django 5.2.5 on 2025-08-23 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skills',
            name='description',
            field=models.TextField(verbose_name='Descripcion'),
        ),
    ]
